"""Create Concerts table

Revision ID: 738aedb9ba51
Revises: b01979c7ce45
Create Date: 2022-09-19 00:05:00.347017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738aedb9ba51'
down_revision = 'b01979c7ce45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), sa.ForeignKey('bands.id'), nullable=False),
    sa.Column('venue_id', sa.Integer(), sa.ForeignKey('venues.id'), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concerts')
    # ### end Alembic commands ###
